export interface PlayerAvatarData {
  id: string;
  name: string;
  gender: 'male' | 'female';
  title: string;
  bio: string;
  accentColor: string;
  personalityHint: string;
  imageUrl: string;
  isDefault: boolean;
}

export const AVATARS_CATALOG: PlayerAvatarData[] = [
  // ── 10 DEFAULT AVATARS (Starter Roster) ──
  {
    id: 'avatar-1',
    name: 'Miguel',
    gender: 'male',
    title: 'The Charismatic Pro',
    bio: 'Sharp, confident cardist with a flair for sudden Tongits and Sapaw plays.',
    accentColor: '#f59e0b',
    personalityHint: 'Balanced & opportunistic',
    imageUrl: '/avatars/avatar-1.jpg',
    isDefault: true,
  },
  {
    id: 'avatar-2',
    name: 'Sofia',
    gender: 'female',
    title: 'The Champagne Queen',
    bio: 'Cool, elegant calculator who conceals secret melds until victory is certain.',
    accentColor: '#ef4444',
    personalityHint: 'Conservative & defensive',
    imageUrl: '/avatars/avatar-2.jpg',
    isDefault: true,
  },
  {
    id: 'avatar-3',
    name: 'Rafael',
    gender: 'male',
    title: 'The Grandmaster',
    bio: 'Distinguished veteran who tracks every discarded card with razor precision.',
    accentColor: '#e2e8f0',
    personalityHint: 'Patient & calculating',
    imageUrl: '/avatars/avatar-3.jpg',
    isDefault: true,
  },
  {
    id: 'avatar-4',
    name: 'Liza',
    gender: 'female',
    title: 'The High-Roller',
    bio: 'Analytical mind who optimizes deadwood down to the single digits.',
    accentColor: '#fbbf24',
    personalityHint: 'Deadwood efficiency expert',
    imageUrl: '/avatars/avatar-4.jpg',
    isDefault: true,
  },
  {
    id: 'avatar-5',
    name: 'Marco',
    gender: 'male',
    title: 'The High-Stakes Baron',
    bio: 'Aggressive tournament regular who pressures opponents with lightning draws.',
    accentColor: '#991b1b',
    personalityHint: 'High-pressure attacks',
    imageUrl: '/avatars/avatar-5.jpg',
    isDefault: true,
  },
  {
    id: 'avatar-6',
    name: 'Andrea',
    gender: 'female',
    title: 'The Rising Phenom',
    bio: 'Energetic and observant cardist with lightning-fast meld execution.',
    accentColor: '#f97316',
    personalityHint: 'Fast & adaptable',
    imageUrl: '/avatars/avatar-6.jpg',
    isDefault: true,
  },
  {
    id: 'avatar-7',
    name: 'Daniel',
    gender: 'male',
    title: 'The Tactician',
    bio: 'Intuitive player whose unorthodox combinations keep opponents guessing.',
    accentColor: '#06b6d4',
    personalityHint: 'Unpredictable & bold',
    imageUrl: '/avatars/avatar-7.jpg',
    isDefault: true,
  },
  {
    id: 'avatar-8',
    name: 'Elena',
    gender: 'female',
    title: 'The Emerald Strategist',
    bio: 'Poised table master who lays down traps and bait discards effortlessly.',
    accentColor: '#10b981',
    personalityHint: 'Tactical baiter',
    imageUrl: '/avatars/avatar-8.jpg',
    isDefault: true,
  },
  {
    id: 'avatar-9',
    name: 'Gabriel',
    gender: 'male',
    title: 'The Table Commander',
    bio: 'Refined champion who dictates game pace from the first turn.',
    accentColor: '#3b82f6',
    personalityHint: 'Dominant pacing',
    imageUrl: '/avatars/avatar-9.jpg',
    isDefault: true,
  },
  {
    id: 'avatar-10',
    name: 'Chloe',
    gender: 'female',
    title: 'The Golden Siren',
    bio: 'Calm and collected champion who strikes with flawless Tongits timing.',
    accentColor: '#eab308',
    personalityHint: 'Master of Tongits timing',
    imageUrl: '/avatars/avatar-10.jpg',
    isDefault: true,
  },

  // ── 15 OPTIONAL / EXTENDED AVATARS ──
  {
    id: 'avatar-11',
    name: 'Mateo',
    gender: 'male',
    title: 'The VIP Illusionist',
    bio: 'Deceptive trickster specializing in concealing run sequences.',
    accentColor: '#a855f7',
    personalityHint: 'Deceptive runs',
    imageUrl: '/avatars/avatar-11.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-12',
    name: 'Carmela',
    gender: 'female',
    title: 'The Ace Dealer',
    bio: 'Former casino croupier who knows every angle of card distribution.',
    accentColor: '#d97706',
    personalityHint: 'Statistical master',
    imageUrl: '/avatars/avatar-12.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-13',
    name: 'Rodrigo',
    gender: 'male',
    title: 'The Crimson Fox',
    bio: 'Smooth risk-taker who excels at daring Sapaw comebacks.',
    accentColor: '#dc2626',
    personalityHint: 'Daring Sapaw risker',
    imageUrl: '/avatars/avatar-13.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-14',
    name: 'Isabella',
    gender: 'female',
    title: 'The Golden Empress',
    bio: 'Reigning high-society table queen with an ironclad defense.',
    accentColor: '#f59e0b',
    personalityHint: 'Ironclad defense',
    imageUrl: '/avatars/avatar-14.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-15',
    name: 'Lucas',
    gender: 'male',
    title: 'The Dapper Gentleman',
    bio: 'Patient counter who calculates pot odds before every single draw.',
    accentColor: '#78716c',
    personalityHint: 'Odds calculator',
    imageUrl: '/avatars/avatar-15.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-16',
    name: 'Beatriz',
    gender: 'female',
    title: 'The Lady Luck',
    bio: 'Naturally gifted competitor whose hands always seem blessed by the cards.',
    accentColor: '#eab308',
    personalityHint: 'High-draw synergy',
    imageUrl: '/avatars/avatar-16.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-17',
    name: 'Eduardo',
    gender: 'male',
    title: 'The Card Maestro',
    bio: 'Old-school master who never forgets which suit opponent is hunting.',
    accentColor: '#64748b',
    personalityHint: 'Suit blocker',
    imageUrl: '/avatars/avatar-17.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-18',
    name: 'Valerie',
    gender: 'female',
    title: 'The Sapphire Queen',
    bio: 'Ice-cold competitor who forces opponents into Sunog burns.',
    accentColor: '#2563eb',
    personalityHint: 'Sunog enforcer',
    imageUrl: '/avatars/avatar-18.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-19',
    name: 'Adrian',
    gender: 'male',
    title: 'The Silent Shark',
    bio: 'Speaks little, plays fast, and strikes with sudden Draw challenges.',
    accentColor: '#334155',
    personalityHint: 'Quick Draw challenger',
    imageUrl: '/avatars/avatar-19.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-20',
    name: 'Maya',
    gender: 'female',
    title: 'The Chip Mistress',
    bio: 'Fearless gambler who turns deadwood disadvantage into gold.',
    accentColor: '#b91c1c',
    personalityHint: 'Aggressive bluffing',
    imageUrl: '/avatars/avatar-20.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-21',
    name: 'Antonio',
    gender: 'male',
    title: 'The Smooth Operator',
    bio: 'Charming player who stays relaxed even when facing big stakes.',
    accentColor: '#f1f5f9',
    personalityHint: 'Unflappable composure',
    imageUrl: '/avatars/avatar-21.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-22',
    name: 'Bianca',
    gender: 'female',
    title: 'The Scarlet Diva',
    bio: 'Dynamic showstopper who delights in high-scoring melds.',
    accentColor: '#e11d48',
    personalityHint: 'Meld maximalist',
    imageUrl: '/avatars/avatar-22.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-23',
    name: 'Fernando',
    gender: 'male',
    title: 'The Syndicate Boss',
    bio: 'Commands the table with calculated moves and zero deadwood waste.',
    accentColor: '#d97706',
    personalityHint: 'Deadwood minimizer',
    imageUrl: '/avatars/avatar-23.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-24',
    name: 'Natalia',
    gender: 'female',
    title: 'The Midnight Enchantress',
    bio: 'Mysterious player known for late-game reversals and quick Tongits.',
    accentColor: '#7c3aed',
    personalityHint: 'Endgame turnaround',
    imageUrl: '/avatars/avatar-24.jpg',
    isDefault: false,
  },
  {
    id: 'avatar-25',
    name: 'Carlos',
    gender: 'male',
    title: 'The Green Felt King',
    bio: 'Legendary table veteran with a sixth sense for winning combinations.',
    accentColor: '#059669',
    personalityHint: 'Master combination maker',
    imageUrl: '/avatars/avatar-25.jpg',
    isDefault: false,
  },
];

export const DEFAULT_AVATARS = AVATARS_CATALOG.filter((a) => a.isDefault);
export const OPTIONAL_AVATARS = AVATARS_CATALOG.filter((a) => !a.isDefault);

export const DEFAULT_AVATAR_ID = 'avatar-1';

// Legacy ID mapping to guarantee backwards-compatibility
const LEGACY_MAP: Record<string, string> = {
  'avatar-miguel': 'avatar-1',
  'avatar-sofia': 'avatar-2',
  'avatar-rafael': 'avatar-3',
  'avatar-liza': 'avatar-4',
  'avatar-marco': 'avatar-5',
  'avatar-andrea': 'avatar-6',
  'avatar-daniel': 'avatar-7',
  'avatar-chloe': 'avatar-10',
};

export function getAvatarData(avatarId?: string): PlayerAvatarData {
  if (!avatarId) return AVATARS_CATALOG[0];
  const normalizedId = LEGACY_MAP[avatarId] || avatarId;
  const match = AVATARS_CATALOG.find((a) => a.id === normalizedId);
  return match || AVATARS_CATALOG[0];
}
